[Checks]
block-opening-brace-space-before=error
double-semicolon=error
double-spaces=error
ellipsis=error
line-length=warn
naming-convention=error
# doesn't account for operands being on different lines, and uncrustify already ensures this anyway
no-space=off
note=warn
space-before-paren=error
use-of-tabs=off
trailing-newlines=error
trailing-whitespace=error
unnecessary-string-template=error

[Disabler]
disable-by-inline-comments=true

[line-length]
max-line-length=120
ignore-comments=true

[naming-convention]
exceptions=UUID,

[note]
keywords=TODO,FIXME,HACK,
